### ISSUE TITLE
Releasing the model and weight files.

### ISSUE THREAD

**Issue by Frost24K** [Mabel0403/CAMP#1]
Hi,
Thank you for sharing this impressive work! I am currently working on a similar project and would like to reproduce your results for comparison with my own methods. I was wondering if you have any plans to release the code and pre-trained weight files. Having access to these resources would be invaluable for benchmarking and advancing my research.

I appreciate your consideration and look forward to your response.

Best.

**Comment by Mabel0403** [comment]
Thank you for your interest in our work! We will be uploading a preliminary version of the code and pre-trained weight files within the next two days for those who wish to explore it quickly. The fully standardized version will be available within a month!

**Comment by Frost24K** [comment]
Thanks for the quick reply!
Best.
