### ISSUE TITLE
Hello, may I ask how to set up the training model if I am unable to connect to the Hugging Face? We look forward to your reply

### ISSUE THREAD

**Issue by sugy0114** [Mabel0403/CAMP#4]

**Comment by Mabel0403** [comment]
Hi, sugy0114,

You can manually download the backbone model from Hugging Face to your local machine and load it into your program.

If you're loading the model locally, you may need to modify the code like this:

`def convnext_base(pretrained=True, in_22k=True, **kwargs):
    model = ConvNeXt(depths=[3, 3, 27, 3], dims=[128, 256, 512, 1024])
    if pretrained:
        url = model_urls['convnext_base_22k'] if in_22k else model_urls['convnext_base_1k']
        checkpoint = torch.hub.load_state_dict_from_url(url=url, map_location="cpu")
        print(url)
        model.load_state_dict(checkpoint["model"], strict=False)
    return model`

to this:

`@register_model
def convnext_base(pretrained=True, in_22k=True, **kwargs):
    model = ConvNeXt(depths=[3, 3, 27, 3], dims=[128, 256, 512, 1024])
    if pretrained:
        # url = model_urls['convnext_base_22k'] if in_22k else model_urls['convnext_base_1k']
        # checkpoint = torch.hub.load_state_dict_from_url(url=url, map_location="cpu")
        # print(url)
        checkpoint = torch.load(r"./your_path_to/convnext_base_22k_1k_224.pth", map_location="cpu")
        model.load_state_dict(checkpoint["model"], strict=False)
    return model`

 This code can be found in [conv](https://github.com/Mabel0403/CAMP/blob/main/sample4geo/hand_convnext/ConvNext/backbones/model_convnext.py)

If you're unable to download the model yourself, feel free to reach out, and I can upload it for you.
