### ISSUE TITLE
What is the backbone used in this article? Do you have pretrain?

### ISSUE THREAD

**Issue by sugy0114** [Mabel0403/CAMP#5]
Looking forward to your reply

**Comment by Mabel0403** [comment]
Hi, we use the ConvNeXt-Base model pre-trained on ImageNet-22k as the backbone. If you're unable to access it directly from Hugging Face, you can download it from the following link: [https://drive.google.com/file/d/1Uf0m0qx91QM1ASPymgJ2BpS1d7IuQKs7/view?usp=sharing
](https://drive.google.com/file/d/1Uf0m0qx91QM1ASPymgJ2BpS1d7IuQKs7/view?usp=sharing
)
