### ISSUE TITLE
Can the article replace the backbone with dinov2? Which part should be replaced？

### ISSUE THREAD

**Issue by sugy0114** [Mabel0403/CAMP#6]
Looking forward to your reply！

**Comment by Mabel0403** [comment]
You can replace the **self.model_1** of **class two_view_net(nn.Module)** in [model.py](https://github.com/Mabel0403/CAMP/blob/main/sample4geo/hand_convnext/model.py). In addition, you may need to adjust the image size for the adaption of dinov2, the settings are all in the [train_university.py](https://github.com/Mabel0403/CAMP/blob/main/train_university.py).
