### ISSUE TITLE
Why are SUES-200.py and university-1652.py, and train_university.py and train_SUES-200.py identical? How should we modify SUES-200 to train it?

### ISSUE THREAD

**Issue by sugy0114** [Mabel0403/CAMP#7]
Looking forward to your reply!

**Comment by Mabel0403** [comment]
You can preprocess the SUES-200 dataset by following the instructions in [README.md](https://github.com/Mabel0403/CAMP#2-for-sues-200-dataset).  The reason we process the U-1652 and SUES-200 datasets separately is that their dataset structures differ, and handling them independently allows for more flexibility when training under different settings.

**Comment by sugy0114** [comment]
> You can preprocess the SUES-200 dataset by following the instructions in [README.md](https://github.com/Mabel0403/CAMP#2-for-sues-200-dataset). The reason we process the U-1652 and SUES-200 datasets separately is that their dataset structures differ, and handling them independently allows for more flexibility when training under different settings.

Why is the given code the same

**Comment by Mabel0403** [comment]
The overall structure is similar, but the data-related components differ.
